FROM rust:latest AS chef
RUN cargo install cargo-chef
RUN apt-get update && apt-get install -y pkg-config libssl-dev libpq-dev build-essential && rm -rf /var/lib/apt/lists/*

FROM chef AS planner
WORKDIR /app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
WORKDIR /app
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook -p test-suite --recipe-path recipe.json
