CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    pin TEXT NULL,
    pic TEXT NULL,
    last_login_at TIMESTAMP NULL,
    character_slots SMALLINT NOT NULL DEFAULT 8,
    gender_wz SMALLINT NOT NULL,
    accepted_tos BOOLEAN NOT NULL DEFAULT FALSE,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    acc_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    world_id SMALLINT NOT NULL,
    map_wz INTEGER NOT NULL,
    ign TEXT NOT NULL,
    level SMALLINT NOT NULL DEFAULT 1,
    exp INTEGER NOT NULL DEFAULT 0,
    strength SMALLINT NOT NULL DEFAULT 4,
    dexterity SMALLINT NOT NULL DEFAULT 4,
    luck SMALLINT NOT NULL DEFAULT 4,
    intelligence SMALLINT NOT NULL DEFAULT 4,
    hp SMALLINT NOT NULL DEFAULT 50,
    mp SMALLINT NOT NULL DEFAULT 5,
    max_hp SMALLINT NOT NULL DEFAULT 50,
    max_mp SMALLINT NOT NULL DEFAULT 0,
    ap SMALLINT NOT NULL DEFAULT 0,
    fame SMALLINT NOT NULL DEFAULT 0,
    meso INTEGER NOT NULL DEFAULT 0,
    job_wz SMALLINT NOT NULL,
    face_wz INTEGER NOT NULL,
    hair_wz INTEGER NOT NULL,
    hair_color_wz INTEGER NOT NULL,
    skin_wz INTEGER NOT NULL,
    gender_wz SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE equip_items (
    id SERIAL PRIMARY KEY,
    char_id INTEGER NULL REFERENCES characters(id) ON DELETE CASCADE,
    wz INTEGER NOT NULL,
    ipos SMALLINT NULL,
    strength INTEGER NOT NULL DEFAULT 0,
    dexterity INTEGER NOT NULL DEFAULT 0,
    intelligence INTEGER NOT NULL DEFAULT 0,
    luck INTEGER NOT NULL DEFAULT 0,
    attack INTEGER NOT NULL DEFAULT 0,
    weapon_defense INTEGER NOT NULL DEFAULT 0,
    magic INTEGER NOT NULL DEFAULT 0,
    magic_defense INTEGER NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL DEFAULT 0,
    mp INTEGER NOT NULL DEFAULT 0,
    accuracy INTEGER NOT NULL DEFAULT 0,
    avoid INTEGER NOT NULL DEFAULT 0,
    hands INTEGER NOT NULL DEFAULT 0,
    speed INTEGER NOT NULL DEFAULT 0,
    jump INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE cash_nonequip_items (
    id SERIAL PRIMARY KEY,
    char_id INTEGER NULL REFERENCES characters(id) ON DELETE CASCADE,
    wz INTEGER NOT NULL,
    ipos SMALLINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE etc_items (
    id SERIAL PRIMARY KEY,
    char_id INTEGER NULL REFERENCES characters(id) ON DELETE CASCADE,
    wz INTEGER NOT NULL,
    ipos SMALLINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE use_items (
    id SERIAL PRIMARY KEY,
    char_id INTEGER NULL REFERENCES characters(id) ON DELETE CASCADE,
    wz INTEGER NOT NULL,
    ipos SMALLINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE setup_items (
    id SERIAL PRIMARY KEY,
    char_id INTEGER NULL REFERENCES characters(id) ON DELETE CASCADE,
    wz INTEGER NOT NULL,
    ipos SMALLINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE character_limits (
    acc_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    world_id SMALLINT NOT NULL,
    char_max SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (acc_id, world_id)
);

CREATE TABLE keybindings (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    key INTEGER NOT NULL,
    bind_type SMALLINT NOT NULL,
    action INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE skills (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    wz INTEGER NOT NULL,
    level SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE accounts
ADD CONSTRAINT accounts_unique UNIQUE (username);

ALTER TABLE characters
ADD CONSTRAINT characters_unique UNIQUE (ign);

ALTER TABLE keybindings
ADD CONSTRAINT keybindings_unique UNIQUE (char_id, key);

ALTER TABLE skills
ADD CONSTRAINT skills_unique UNIQUE (char_id, wz);



