CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    pin TEXT NULL,
    pic TEXT NULL,
    last_login_at TIMESTAMP NULL,
    character_slots SMALLINT NOT NULL DEFAULT 8,
    gender_id SMALLINT NOT NULL,
    accepted_tos BOOLEAN NOT NULL DEFAULT FALSE,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    session_id INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    acc_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    world_id SMALLINT NOT NULL,
    ign TEXT NOT NULL,
    level SMALLINT NOT NULL DEFAULT 1,
    exp INTEGER NOT NULL DEFAULT 0,
    strength SMALLINT NOT NULL DEFAULT 4,
    dexterity SMALLINT NOT NULL DEFAULT 4,
    luck SMALLINT NOT NULL DEFAULT 4,
    intelligence SMALLINT NOT NULL DEFAULT 4,
    hp SMALLINT NOT NULL DEFAULT 50,
    mp SMALLINT NOT NULL DEFAULT 5,
    max_hp SMALLINT NOT NULL DEFAULT 50,
    max_mp SMALLINT NOT NULL DEFAULT 0,
    ap SMALLINT NOT NULL DEFAULT 0,
    fame SMALLINT NOT NULL DEFAULT 0,
    meso INTEGER NOT NULL DEFAULT 0,
    job_id SMALLINT NOT NULL,
    face_id INTEGER NOT NULL,
    hair_id INTEGER NOT NULL,
    hair_color_id INTEGER NOT NULL,
    skin_id INTEGER NOT NULL,
    gender_id SMALLINT NOT NULL,
    map_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE equips (
    id SERIAL PRIMARY KEY,
    wz_id INTEGER NOT NULL,
    strength INTEGER DEFAULT 0,
    dexterity INTEGER DEFAULT 0,
    intelligence INTEGER DEFAULT 0,
    luck INTEGER DEFAULT 0,
    attack INTEGER DEFAULT 0,
    weapon_defense INTEGER DEFAULT 0,
    magic INTEGER DEFAULT 0,
    magic_defense INTEGER DEFAULT 0,
    hp INTEGER DEFAULT 0,
    mp INTEGER DEFAULT 0,
    accuracy INTEGER DEFAULT 0,
    avoid INTEGER DEFAULT 0,
    hands INTEGER DEFAULT 0,
    speed INTEGER DEFAULT 0,
    jump INTEGER DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE regular_equipment_set (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    hat INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    pants INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    face_acc INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    eye_acc INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    ear_acc INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    top INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    bottom INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    shoes INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    gloves INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    cape INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    weapon INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    shield INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    saddle INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    tamed_mob INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    subweapon INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    belt INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    pendant_one INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    pendant_two INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    ring_one INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    ring_two INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    ring_three INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    ring_four INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    shoulder INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    emblem INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    medal INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    badge INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    android INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    heart INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    book INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    pocket INTEGER NULL REFERENCES equips(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE cash_equipment_set (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    ring_one INTEGER NULL,
    ring_two INTEGER NULL,
    ring_three INTEGER NULL,
    ring_four INTEGER NULL,
    hat INTEGER NULL,
    face_acc INTEGER NULL,
    hair INTEGER NULL,
    pendant INTEGER NULL,
    weapon INTEGER NULL,
    belt INTEGER NULL,
    top INTEGER NULL,
    bottom INTEGER NULL,
    shoes INTEGER NULL,
    ear_acc INTEGER NULL,
    shoulder INTEGER NULL,
    subweapon INTEGER NULL,
    cape INTEGER NULL,
    gloves INTEGER NULL,
    eye_acc INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE pet_equipment_set (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    pet_one_acc INTEGER NULL,
    pet_two_acc INTEGER NULL,
    pet_three_acc INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE android_equipment_set (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    android_hat INTEGER NULL,
    android_face INTEGER NULL,
    android_top INTEGER NULL,
    android_bottom INTEGER NULL,
    android_gloves INTEGER NULL,
    android_cape INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE character_limits (
    acc_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    world_id SMALLINT NOT NULL,
    char_max SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (acc_id, world_id)
);

CREATE TABLE keybindings (
    id SERIAL PRIMARY KEY,
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    key INTEGER NOT NULL,
    bind_type SMALLINT NOT NULL,
    action INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE keybindings
ADD CONSTRAINT key_is_unique_per_character UNIQUE (char_id, key);

CREATE TABLE skills (
    char_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    skill_id INTEGER NOT NULL,
    level SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);



