use crate::inc::helpers;
use crate::models::character::error::CharacterError;
use crate::models::character::model::{CashEquipment, Character, CharacterEquipment};
use crate::models::error::ModelError;
use crate::net::packet::core::Packet;
use crate::net::packet::error::PacketError;
use crate::net::packet::io::error::IOError::WriteError;
use crate::prelude::*;

pub fn write_char_meta(packet: &mut Packet, char: &Character) -> Result<(), ModelError> {
    packet
        .write_int(char.id)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_str(&char.ign)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_bytes(&vec![0u8; 13 - char.ign.len()])
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_byte(char.gender as u8)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_byte(char.skin as u8)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_int(char.face)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_int(char.hair)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    // Pets... Not implemented yet
    packet
        .write_long(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_long(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_long(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_byte(char.level.ok_or(CharacterError::MissingField)? as u8)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.job)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.strength.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.dexterity.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.intelligence.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.luck.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.hp.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.max_hp.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.mp.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.max_mp.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.ap.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    // SP
    packet
        .write_short(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_int(char.exp.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_short(char.fame.ok_or(CharacterError::MissingField)?)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    // Gach xp?
    packet
        .write_int(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_int(char.map)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_byte(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    packet
        .write_int(0)
        .map_err(WriteError)
        .map_err(PacketError::from)
        .map_err(CharacterError::from)
        .map_err(ModelError::from)?;
    Ok(())
}
